//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aeriksa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airquality
    {
        public int id { get; set; }
        public Nullable<System.DateTime> recordeddate { get; set; }
        public Nullable<int> CO2 { get; set; }
        public Nullable<int> PM10 { get; set; }
        public Nullable<int> PM2_5 { get; set; }
        public string Temperature_High { get; set; }
        public string Temperature_Low { get; set; }
        public Nullable<int> PM3 { get; set; }
        public Nullable<int> Humidity { get; set; }
    }
}
